name:                aoc2018-haskell
version:             0.1.0.0
github:              brabster/advent-of-code-2018-haskell"
license:             BSD3
author:              "Paul Brabban"
maintainer:          "paul.brabban@gmail.com"
copyright:           "2019 Paul Brabban"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/brabster/advent-of-code-2018-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- regex-compat
- matrices

library:
  source-dirs: src

executables:
  aoc-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2018-haskell

tests:
  aoc-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2018-haskell
    - hspec
